[project]
name = "approx-opaque-topk-wllm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy==1.24.4",
"pandas==2.0.3",
"tzdata==2025.2",
"pyarrow==17.0.0"]
